name: Deploy front to s3 prod (Manual, lp. subdomain, no CF redirect rules)

on: [workflow_dispatch]
jobs:
  deploy:
    name: Deploy com
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: mv .env_prod_com_lp .env.production
      - run: npm ci
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_KEY }}
          aws-region: ap-east-1
      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./public/ s3://lp.oqtima.com --delete --exclude "*" --include "*.html" --include "page-data/*" --include "app-data.json" --include "scripts/registration-popup-script*.js" --cache-control "public, max-age=0, must-revalidate"
          aws s3 sync ./public/ s3://lp.oqtima.com --delete --exclude "*.html" --exclude "page-data/*" --exclude "app-data.json" --exclude "scripts/registration-popup-script*.js" --cache-control "public, max-age=31536000, immutable"
          aws s3 cp ./public/sw.js s3://lp.oqtima.com/sw.js --cache-control "public, max-age=0, must-revalidate"
